---
- name: "Playbook Runner"
  hosts: all
  vars:
    switches: "cr"  # Default: run all roles (common, rollup)
    wipe: false
    data_availability_role: "mock_da"  # Default DA role (overridden by inventory or -e)
  pre_tasks:
    - import_tasks: load_vars.yaml

    - name: check switches parameter is provided
      assert:
        that: switches | length > 0
        fail_msg: "Please specify 'switches' parameter (e.g., -e switches=cr). Valid values: 'c' (common), 'r' (rollup), 'h' (hyperlane), 'p' (proxy)."
    - name: import preconditions
      import_tasks: preconditions.yaml
  roles:
    - role: "./roles/common"
      when: "'c' in switches"
    - role: "./roles/rollup"
      when: "'r' in switches"
    - role: "./roles/hyperlane"
      when: "'h' in switches"
    - role: "./roles/proxy"
      when: "'p' in switches"
