---
- name: restart hyperlane alloy
  become: true
  systemd:
    name: alloy
    state: restarted

- name: restart hyperlane telegraf
  become: true
  systemd:
    name: telegraf
    state: restarted
